### ISSUE TITLE
Set Up ElasticSearch to use Credentials (instead of IP whitelist)

### ISSUE THREAD

**Issue by Unix-Code** [chilipot/TRACE-API#39]
Currently, our ES instance has IP whitelisting, which requires being updated with our new public IP's every so often (we don't have static IP's). Either we need an integration server with the API on it that has a static IP, or we need to set up credentials.

**Comment by danguddemi** [comment]
Elasticsearch access is limited to a VPC only.
Public access to the instance has been removed
